workflows:
  android_build:
    name: Build Android App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - google_play # Ce groupe est ici pour maintenir la structure de ton workflow, mais il n'est pas nécessaire pour la publication.
      vars:
        PACKAGE_NAME: "com.example.yourapp"
    scripts:
      - name: Clean npm cache and reinstall dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Install Android dependencies
        script: |
          # Installer les dépendances Android nécessaires (si non déjà faites dans `npm install`)
          cd android
          ./gradlew clean
          
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild

      - name: Set up app/build.gradle
        script: |
          mv ./support-files/build.gradle android/app

      - name: Build Android APK
        script: |
          # Exécuter la construction de l'APK
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk
